// <auto-generated />
using BattleGameApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleGameApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BattleGameApi.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("LevelRequired")
                        .HasColumnType("int");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetId = 1,
                            AssetName = "Hero 1",
                            LevelRequired = 0
                        },
                        new
                        {
                            AssetId = 2,
                            AssetName = "Hero 2",
                            LevelRequired = 0
                        });
                });

            modelBuilder.Entity("BattleGameApi.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Age = 20,
                            FullName = "Player One",
                            Level = 10,
                            PlayerName = "Player 1"
                        },
                        new
                        {
                            PlayerId = 2,
                            Age = 19,
                            FullName = "Player Two",
                            Level = 3,
                            PlayerName = "Player 2"
                        },
                        new
                        {
                            PlayerId = 3,
                            Age = 23,
                            FullName = "Player Three",
                            Level = 10,
                            PlayerName = "Player 3"
                        });
                });

            modelBuilder.Entity("BattleGameApi.Models.PlayerAsset", b =>
                {
                    b.Property<int>("PlayerAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerAssetId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("PlayerAssetId");

                    b.HasIndex("AssetId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAssets");

                    b.HasData(
                        new
                        {
                            PlayerAssetId = 1,
                            AssetId = 1,
                            PlayerId = 1
                        },
                        new
                        {
                            PlayerAssetId = 2,
                            AssetId = 2,
                            PlayerId = 2
                        },
                        new
                        {
                            PlayerAssetId = 3,
                            AssetId = 1,
                            PlayerId = 3
                        });
                });

            modelBuilder.Entity("BattleGameApi.Models.PlayerAsset", b =>
                {
                    b.HasOne("BattleGameApi.Models.Asset", "Asset")
                        .WithMany("PlayerAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleGameApi.Models.Player", "Player")
                        .WithMany("PlayerAssets")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BattleGameApi.Models.Asset", b =>
                {
                    b.Navigation("PlayerAssets");
                });

            modelBuilder.Entity("BattleGameApi.Models.Player", b =>
                {
                    b.Navigation("PlayerAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
